version: '3'
services:
  mongo:
    container_name: mongo-for-talmud
    restart: on-failure
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "./mongo-data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    container_name: backend-for-talmud
    restart: always
    image: ${IMAGE}
    ports:
      - 80:3000
    env_file:
      - .env-backend
