version: '3'
services:
  mongo:
    container_name: mongo-for-talmud
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "./mongo-data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret


