version: '3'
services:
  mongo:
    container_name: mongo-for-talmud
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "./mongo-data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    container_name: backend-for-talmud
    image: 424334533647.dkr.ecr.eu-west-1.amazonaws.com/talmud
    ports:
      - 3000:3000
    env_file:
      - .env-backend
