name: SSH test

on:

  workflow_dispatch:


jobs:
  run_example_job:
    name: deploy test
    environment:
      name: staging
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: Build        
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: 'eu-west-1'
      run: |
          echo "::set-env name=IMAGE::image-test"
          echo "::set-env name=IMAGE2::image-test"
    - name: copy file via ssh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose-backend.template.yml"
        target: .
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      env:
        IMAGE: ${{ steps.vars.outputs.image }}
        TEST: "yaron-test"
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        envs: IMAGE,TEST
        command_timeout: 30m
        script: | 

          echo "Nice Job!!! image $IMAGE image2 $IMAGE2 $TEST"
