name: Deploy to staging

on:

  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    
    steps:
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.SSH_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              echo "test $IMAGE_REGISTRY"
              printenv
              docker-compose -f docker-compose-backend.yml down
              docker-compose -f docker-compose-backend.yml up --detach
              '
