name: Deploy to staging

on:

  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    
    steps:
      - uses: actions/checkout@v3
      - name: Build        
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'eu-west-1'
        run: |
            echo "test $AWS_ACCESS_KEY_ID"
            aws sts get-caller-identity
            make upload

      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.SSH_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              source ~/.bash_profile
              aws ecr get-login-password  | docker login --username AWS --password-stdin $IMAGE_REGISTRY
              docker-compose -f docker-compose-backend.yml down
              docker-compose -f docker-compose-backend.yml up --detach
              '
